---
- hosts: "{{ host }}"
  become: yes
  gather_facts: no
  tasks:
    - name: Fetch Hex
      shell: >
        mix local.hex --force
      args:
        chdir: "{{ project_dir }}"

    - name: Compile the app
      shell: mix compile
      args:
        chdir: "{{ project_dir }}"

    - name: Build production release for app
      shell: >
        MIX_ENV=prod
        mix release --env=prod --name={{ app }}
      args:
        chdir: "{{ project_dir }}"

    - name: Remove old release from synced release folder
      file:
        path: /vagrant/releases/{{ app }}.tar.gz
        state: absent

    - name: Copy release to synced release folder
      shell: >
        cp
        _build/prod/rel/{{ app }}/releases/0.1.0/{{ app }}.tar.gz
        /vagrant/releases/
      args:
        chdir: "{{ project_dir }}"
