---
- hosts: "{{ host }}"
  become: yes
  vars_files:
   - vars/main.yml
  roles:
   - role: geerlingguy.nodejs
  tasks:
    - name: Install Git
      package: name=git state=present

    - name: Add Erlang Solutions repo
      apt_repository: repo="deb https://packages.erlang-solutions.com/debian trusty contrib"

    - name: Add Erlang Solusion repo key
      apt_key: url="https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc"

    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=86400

    - name: Install Erlang/OTP
      apt: name=esl-erlang state=installed force=yes

    - name: Install Elixir
      apt: name=elixir state=installed force=yes

    - name: Install Phoenix
      command: mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez --force

    - name: ensure packages are installed
      apt: name={{item}}
      with_items:
          - postgresql
          - libpq-dev
          - python-psycopg2

- include: postgresql_dev.yml
