---
- hosts: "{{ host }}"
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Install python2
      raw: sudo apt-get -y install python-simplejson
  tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=86400

    - name: ensure packages are installed
      apt: name={{item}}
      with_items:
          - postgresql
          - libpq-dev
          - python-psycopg2

- include: postgresql_prod.yml
